from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import selenium

#print("Welcome to GoFish tools")
print("Welcome To GoFish")
time.sleep(1)
print("This Software is for Security Testing")
print("----------------------ONLY----------------------")
print("                                                  .-')    ('-. .-. ")
print("                                                 ( 00 ). ( 00 )  / ")
print("  ,----.    .-'),-----.          ,------.,-.-') (_)---\_),--. ,--. ")
print(" '  .-./-')( 00'  .-.  '      ('-| _.---'|  |00)/    _ | |  | |  | ")
print(" |  |_( 00 )   |  | |  |      (00|(_|    |  |  |\  :` `. |   .|  | ")
print(" |  | .--, \_) |  |\|  |      /  |  '--. |  |(_/ '\.`''.)|       | ")
print("(|  | '. (_/ \ |  | |  |      \_)|  .--',|  |_.'.-._)   \|  .-.  | ")
print(" |  '--'  |   `'  '-'  '        \|  |_)(_|  |   \       /|  | |  | ")
print("  `------'      `-----'          `--'    `--'    `-----' `--' `--' ")
time.sleep(1)
print("-------------------------------------")
print(" )\ )    )    ) (       )    )       ") 
print("(()/( ( /( ( /( )\ ) ( /( ( /(       ")
print(" /(_)))\()))\()|()/( )\()))\())`  )  ") 
print("(_)) ((_)\((_)\ /(_)|_))/((_)\ /(/(  ") 
print("| _ \/  (_)  (_|_) _| |_ /  (_|(_)_\ ") 
print("|   / () | () | |  _|  _| () || '_ \)") 
print("|_|_\ __/ \__/  |_|  \__|\__/ | .__/ ") 
print("                              |_|    ") 
print("-------------------------------------")
time.sleep(1)
print("Use Editor to input Credentials")
print("On Lines 17 & 19")
time.sleep(1)
print("Entering Facebook")
driver=webdriver.Chrome('C:/Users/R00ft0p/Documents/GoFish/chromedriver_win32/chromedriver')
driver.get('https://facebook.com')
time.sleep(4)

user=driver.find_element_by_css_selector('#email') 
user.send_keys('') # Enter email or preffered Login Id
password=driver.find_element_by_css_selector('#pass')
password.send_keys('') # Enter Password
login=driver.find_element_by_css_selector('#loginbutton')
login.click()
time.sleep(2)
print("We are In!!")
driver.get('https://www.facebook.com/settings')
print("Entered Settings Page")
time.sleep(1)
rqstbtn=driver.find_element_by_xpath('//*[@id="SettingsPage_Content"]/div/a')
#print("below is the print")# for debug
#print(rqstbtn)  #for debug
rqstbtn.send_keys(Keys.ENTER)
time.sleep(1)
print("Requesting Raw Archive Data")
startarchive=driver.find_element_by_css_selector('#u_jsonp_2_0 > button')
time.sleep(1)
startarchive.send_keys(Keys.ENTER)
print("confirming archive")
time.sleep(4)
confirmpass=driver.find_element_by_xpath('//*[@id="ajax_password"]')

if  confirmpass.is_displayed():

	confirmpass.send_keys('')
	time.sleep(1)
	confirmpass.send_keys(Keys.ENTER)
	print("Downloading Archive")
	print(".")
	time.sleep(1)
	

	print("             (`-')  (`-')  _ <-.(`-')   _     <-. (`-')_           ") 
	print("    .->   <-.(oO )  (OO ).-/  __( Oo)  (_)       \( OO) )    .->   ") 
	print(" ,---(`-'),------,) / ,---.  '-'---.\  ,-(`-'),--./ ,--/  ,---(`-')")
	print("'  .-(OO )|   /`. ' | \ /`.\ | .-. (/  | ( OO)|   \ |  | '  .-(Oo )") 
	print("|  | .-, \|  |_.' | '-'|_.' || '-' `.) |  |  )|  . '|  |)|  | .-, |")
	print("|  | '.(_/|  .   .'(|  .-.  || /`'.  |(|  |_/ |  |\    | |  | '.(_/") 
	print("|  '-'  | |  |\  \  |  | |  || '--'  / |  |'->|  | \   | |  '-'  | ")
	print(" `-----'  `--' '--' `--' `--'`------'  `--'   `--'  `--'  `-----'  ") 
	print("             _(`-')    (`-')  _ (`-')     (`-')  _                 ")
	print("            ( (OO ).-> (oO ).-/ ( Oo).->  (OO ).-/                 ") 
	print("     (`-')   \    .'_  / ,---.  /    '._  / ,---.    ('')          ")                                                         
	print("     ( oO).->'`'-..__) | \ /`.\ |'--...__)| \ /`.\  ( Oo).->       ")
	print("    (,------.|  |  ' | '-'|_.' |`--.  .--''-'|_.' |(,------.       ") 
	print("     `------'|  |  / :(|  .-.  |   |  |  (|  .-.  | `------'       ") 
	print("             |  '-'  / |  | |  |   |  |   |  | |  |                ")
	print("             `------'  `--' `--'   `--'   `--' `--'                ")
	print('FB Archive is now in your download folder/directory')
	time.sleep(2)
	print('Use pip to install fbchat_archive_parser')
	time.sleep(3)
	print("GoFish Is Developing a Parser for Archive Soon")
	driver.close()
	
else:
	time.sleep(2)
	confirmarchive=driver.find_element_by_xpath('//*[@id="u_o_1"]/div[3]/div/button')
	confirmarchive.click()
	print("Requested Archive!!")
	time.sleep(2)
	print("waiting 4 min's to refresh page for FB Data")
	time.sleep(240)
	driver.get('https://www.facebook.com/dyi?')
	time.sleep(2)
	confirmpass.send_keys('')
	time.sleep(1)
	confirmpass.send_keys(Keys.ENTER)
	print("Downloading Archive")
	print(".")
	time.sleep(1)
	print("             (`-')  (`-')  _ <-.(`-')   _     <-. (`-')_           ") 
	print("    .->   <-.(oO )  (OO ).-/  __( Oo)  (_)       \( OO) )    .->   ") 
	print(" ,---(`-'),------,) / ,---.  '-'---.\  ,-(`-'),--./ ,--/  ,---(`-')")
	print("'  .-(OO )|   /`. ' | \ /`.\ | .-. (/  | ( OO)|   \ |  | '  .-(Oo )") 
	print("|  | .-, \|  |_.' | '-'|_.' || '-' `.) |  |  )|  . '|  |)|  | .-, |")
	print("|  | '.(_/|  .   .'(|  .-.  || /`'.  |(|  |_/ |  |\    | |  | '.(_/") 
	print("|  '-'  | |  |\  \  |  | |  || '--'  / |  |'->|  | \   | |  '-'  | ")
	print(" `-----'  `--' '--' `--' `--'`------'  `--'   `--'  `--'  `-----'  ") 
	print("             _(`-')    (`-')  _ (`-')     (`-')  _                 ")
	print("            ( (OO ).-> (oO ).-/ ( Oo).->  (OO ).-/                 ") 
	print("     (`-')   \    .'_  / ,---.  /    '._  / ,---.    ('')          ")                                                         
	print("     ( oO).->'`'-..__) | \ /`.\ |'--...__)| \ /`.\  ( Oo).->       ")
	print("    (,------.|  |  ' | '-'|_.' |`--.  .--''-'|_.' |(,------.       ") 
	print("     `------'|  |  / :(|  .-.  |   |  |  (|  .-.  | `------'       ") 
	print("             |  '-'  / |  | |  |   |  |   |  | |  |                ")
	print("             `------'  `--' `--'   `--'   `--' `--'                ")
	time.sleep(1)
	print('FB Archive is now in your download folder/directory')
	time.sleep(2)
	print('Use pip to install fbchat_archive_parser')
	time.sleep(3)
	print("GoFish Is Developing a Parser for Archive Soon")

	driver.close()