import time
from selenium import webdriver
import datetime as dt
hr=dt.datetime.now().hour
sc=dt.datetime.now().second
mn=dt.datetime.now().minute
dy=dt.datetime.now().day
yr=dt.datetime.now().year
print("                                                                  ")
print("                                          _      (`-').-> (`-').->") 
print("    .->        .->               <-.     (_)     ( OO)_   (OO )__ ") 
print(" ,---(`-')(`-')----.  (`-')   (`-')-----.,-(`-')(_)--\_) ,--. ,'-'") 
print("'  .-(OO )( OO).-.  ' ( OO).->(OO|(_\---'| ( OO)/    _ / |  | |  |") 
print("|  | .-, \( _) | |  |(,------. / |  '--. |  |  )\_..`--. |  `-'  |") 
print("|  | '.(_/ \|  |)|  | `------' \_)  .--'(|  |_/ .-._)   \|  .-.  |") 
print("|  '-'  |   '  '-'  '           `|  |_)  |  |'->\       /|  | |  |") 
print(" `-----'     `-----'             `--'    `--'    `-----' `--' `--'") 
print("        <-. (`-')   (`-')  _ <-.(`-')  (`-')  _   (`-')           ") 
print("           \(OO )_  (OO ).-/  __( OO)  ( OO).-/<-.(OO )           ") 
print("        ,--./  ,-.) / ,---.  '-'. ,--.(,------.,------,)          ") 
print("        |   `.'   | | \ /`.\ |  .'   / |  .---'|   /`. '          ") 
print("        |  |'.'|  | '-'|_.' ||      /)(|  '--. |  |_.' |          ") 
print("        |  |   |  |(|  .-.  ||  .   '  |  .--' |  .   .'          ") 
print("        |  |   |  | |  | |  ||  |\   \ |  `---.|  |\  \           ") 
print("        `--'   `--' `--' `--'`--' '--' `------'`--' '--'          ") 
print("     (`-')            (`-')            (`-')            (`-')     ") 
print("     ( OO).->         ( OO).->         ( OO).->         ( OO).->  ") 
print("    (,------.   (`-')(,------.   (`-')(,------.   (`-')(,------.  ") 
print("     `------'<-.(OO ) `------'<-.(OO ) `------'<-.(OO ) `------'  ") 
print("             ,------.)        ,------.)        ,------.)          ") 
print("             `------'         `------'         `------'           ") 
time.sleep(4)

Clonename = "Yanet Garcia"
newCloneFirstName="Cindy"
newCloneLastName="Feathersworth"
clonesPassword="ThisIsYourSecretPassword"
clonesDOByr="1990"
clonesDOBmnth="1"
clonesDOBdt="1"
uniqueId=hr+sc+mn+dy+yr*hr*sc*mn*dy*yr
print("Launching GoFish Profile Maker")
print(uniqueId)
time.sleep(2)
time.sleep(.1)
print("                                              ")	
print("                                            ,:")
print("                                          ,' |")
print("                                         /   :")
print("                                      --'   / ")
print("                                      \/ /:/  ")
print("                                      / ://_\ ")
print("                                   __/   /    ")
print("                                   )'-. /     ")
print("                                   ./  :\     ")
print("                                    /.' '     ")
print("                                  '/'         ")
time.sleep(2)
print("                                  +           ")
time.sleep(.1)
print("                                 '            ")
time.sleep(.1)
print("                               +.             ")
time.sleep(.1)
print("                           .  *               ")
time.sleep(.1)
print("                          (    |              ")
time.sleep(.1)
print("                       . .-'  '.              ")
time.sleep(.1)
print("                      ( (.   )(:              ")
time.sleep(.1)
print("                  .'    / (_  )               ")
time.sleep(.1)
print("                   _. :(.   )()  `            ")
time.sleep(.1)
print("               .  (  `-' (  `.   .            ")
time.sleep(.1)
print("                .  :  (   .)(                 ")
time.sleep(.1)
print("               /_`( *  ` . )*'                ")
time.sleep(.1)
print("           (  (/  .  ' )++'                   ")
time.sleep(.1)
print("          (   (    )  .+*                     ")
time.sleep(.1)
print("            (`'++.( _(   (                    ")
time.sleep(.1)
print("         ..-. `++    ) `  )  +                ")
time.sleep(.1)
print("       -'   (      ++++  )                    ")
time.sleep(.1)
print("     '    _  `    (+++++                      ")
time.sleep(.1)
print("   _(    (    )+  -`.  ) +                    ")
time.sleep(.1)
print("  (  )  ( _.++* _    \(                       ")
time.sleep(.1)
print("+  )/    (++   (++    )  )                    ")
time.sleep(.1)
print("   (+++   *     `*`                           ")
time.sleep(.1)
print(" )\ )    )    ) (       )    )       ") 
time.sleep(.1)
print("(()/( ( /( ( /( )\ ) ( /( ( /(       ")
time.sleep(.1)
print(" /(_)))\()))\()|()/( )\()))\())`  )  ")
time.sleep(.1) 
print("(_)) ((_)\((_)\ /(_)|_))/((_)\ /(/(  ")
time.sleep(.1) 
print("| _ \/  (_)  (_|_) _| |_ /  (_|(_)_\ ")
time.sleep(.2) 
print("|   / () | () | |  _|  _| () || '_ \)") 
time.sleep(.2)
print("|_|_\ __/ \__/  |_|  \__|\__/ | .__/ ") 
time.sleep(.2)
print("                              |_|    ") 
time.sleep(.1)
print("Your Targets Name to Clone  is "+Clonename)
print("Your uniqueId is ",uniqueId)
print("Your Clone's Name Will Be "+newCloneFirstName,newCloneLastName)
driver = webdriver.Chrome('C:/Users/R00ft0p/Documents/GoFish/chromedriver_win32/chromedriver')  # Optional argument, if not specified will search path.
# driver.set_window_size(100,100)
#print("Hidding Window")
time.sleep(1)
driver.get('https://www.mail.com/int/')
time.sleep(1)
signUpButton=driver.find_element_by_id('signup-button')
signUpButton.click()
inputName=driver.find_element_by_id('idb')
inputName.send_keys(newCloneFirstName)
time.sleep(1)
inputLastName=driver.find_element_by_id('idd')
inputLastName.send_keys(newCloneLastName)
time.sleep(1)
selectGender=driver.find_element_by_id('idf')
selectGender.click
time.sleep(1)
selectDOBm=driver.find_element_by_id('id14')
selectDOBm.click()
selectJan=driver.find_element_by_xpath('//*[@id="id14"]')
selectJan.click()

print("Entering Google Search")
driver.get('http://www.google.com');
time.sleep(1) # Let the user actually see something!
print("Searching By Name")
search_box = driver.find_element_by_name('q')
search_box.send_keys(Clonename)
search_box.submit()
print("Searching for "+Clonename)
time.sleep(2)
print("Searching for Images")
imageButton=driver.find_element_by_xpath('//*[@id="hdtb-msb-vis"]/div[3]/a')
imageButton.click()
time.sleep(4)
print("Selecting First Image via Xpath")
firstImage=driver.find_element_by_xpath('//*[@id="rg_s"]/div[1]/a/img')
firstImage.click()
print("Saving fisrt Image")
imagesavebutton=driver.find_element_by_xpath('//*[@id="irc_cc"]/div[2]/div[3]/div[1]/div/table[1]/tbody/tr/td[3]/a[1]')
imagesavebutton.click()
print("Now Creating Email")
print("As "+Clonename, uniqueId)
print("selecting more options")
moreOptions=driver.find_element_by_xpath('//*[@id="view_container"]/form/div[2]/div/div[2]/div[2]/div')
moreOptions.click()
print("selecting create Account")
creatAccnt=driver.find_element_by_xpath('//*[@id="SIGNUP"]/div')
creatAccnt.click()
print("Creating Account")
time.sleep(2)
firstnameInput=driver.find_element_by_id('FirstName')
firstnameInput.send_keys(newCloneFirstName)
print("next")
lastnameInput=driver.find_element_by_id('LastName')
lastnameInput.send_keys(newCloneLastName)
print("next")
NewuseridInput=driver.find_element_by_id('GmailAddress')
print("next")
NewuseridInput.send_keys(newCloneFirstName)
print("next")
NewuseridInput.send_keys(newCloneLastName)
print("next")
NewuseridInput.send_keys(uniqueId)
print("next")
print(uniqueId)
passwdInput=driver.find_element_by_id('Passwd')
passwdInput.send_keys(clonesPassword)
print("next")
passwdInputAgain=driver.find_element_by_id('PasswdAgain')
passwdInputAgain.send_keys(clonesPassword)
print("next")
mnthSelect=driver.find_element_by_xpath('//*[@id="BirthMonth"]/div')
mnthSelect.click()

print("next")
time.sleep(.2)
firstmnth=driver.find_element_by_xpath('//*[@id=":1"]/div')
firstmnth.click()
print("next")
time.sleep(.2)
birthDayInput=driver.find_element_by_id('BirthDay')
birthDayInput.send_keys(clonesDOBdt)
birthYrInput=driver.find_element_by_id('BirthYear')
birthYrInput.send_keys(clonesDOByr)
genderSelect=driver.find_element_by_xpath('//*[@id="Gender"]/div')
genderSelect.click()
femaleSelect=driver.find_element_by_xpath('//*[@id=":e"]')
femaleSelect.click()
submitButton=driver.find_element_by_id('submitbutton')
submitButton.click()
blueButton=driver.find_element_by_xpath('//*[@id="tos-scroll-button"]/div/img')
blueButton.click()
time.sleep(1)
print("   .-')  ") 
print(" _(  OO) ") 
print("(,------.") 
print(" '------'")
print("  ( )    ")
time.sleep(1)
print("    ( )  ")
time.sleep(.2)
print("     ( ) ")
time.sleep(.2)
blueButton.click()
print("      ( )")
time.sleep(.2)
print("     ( ) ")
time.sleep(.2)
print("    ()   ")
time.sleep(.2)          
print("   ()    ")
time.sleep(.2)         
print("  ()     ")
time.sleep(.2)          
print(" ()      ")
time.sleep(1)
print("  ()     ")
time.sleep(.1)
print("   ()    ")
time.sleep(.1)
print("    ()   ")
time.sleep(.1)
print("     ( ) ")
time.sleep(.1)
print("      ( )")
time.sleep(.1)
print("     ( ) ")
time.sleep(.1)
print("    ( )  ")
time.sleep(.1)
print("  ( )    ")
time.sleep(.1)
print("  ( )    ")
time.sleep(1)
print("    ( )  ")
time.sleep(.1)
print("     ( ) ")
time.sleep(.1)
print("      ( )")
time.sleep(.1)
print("     ( ) ")
time.sleep(.1)
print("    ()   ")
time.sleep(.1)          
print("   ()    ")
time.sleep(.1)         
print("  ()     ")
time.sleep(.1)          
print(" ()      ")
time.sleep(1)
print("  ()     ")
time.sleep(.1)
#blueButton.click()
print("   ()    ")
print("    ()   ")
print("     ( ) ")
print("      ( )")
print("     ( ) ")
print("    ( )  ")
print("  ( )    ")
print("  ( )    ")
time.sleep(.2)
print("    ( )  ")
print("     ( ) ")
print("      ( )")
print("     ( ) ")
print("    ()   ")          
print("   ()    ")         
print("  ()     ")          
print(" ()      ")
time.sleep(.1)
#blueButton.click()
print("  ()     ")
print("   ()    ")
print("    ()   ")
print("     ( ) ")
print("      ( )")
print("     ( ) ")
print("    ( )  ")
print("  ( )    ")
print("  (`-.   ") 
print(" (00  )_ ") 
print(",------.)") 
print("`------' ") 
iagreeButton=driver.find_element_by_id('iagreebutton')
iagreeButton.click()


